"""Wiki schema blueprint — Karpathy LLM-Wiki pattern (AB#2188).

Declares the structure and conventions of a vault as a single ``schema.md``
file at the vault root. Readable by both humans and LLMs. Designed to be
loaded by ``ingest`` and ``query`` to orient the LLM before it writes.

Three operations:
  - init     : create ``schema.md`` from template (refuse if exists, --force overwrites)
  - validate : check the schema's claims match the actual vault state
  - show     : parse and dump the schema as a JSON object

Zero-dep. Reuses ``scanner.parse_frontmatter``.
"""

from __future__ import annotations

import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from .scanner import find_md_files, parse_frontmatter

SCHEMA_FILENAME = "schema.md"

PATH_FIELDS = ("entity_paths", "concept_paths", "synthesis_paths", "raw_paths")
LIST_FIELDS = PATH_FIELDS + ("required_frontmatter", "page_types")


def _now_iso() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def find_schema(vault: Path) -> Path | None:
    """Return the schema.md path if present at the vault root, else None."""
    candidate = vault / SCHEMA_FILENAME
    if candidate.is_file():
        return candidate
    # Case-insensitive fallback (Windows / macOS-default)
    for child in vault.iterdir():
        if child.is_file() and child.name.lower() == SCHEMA_FILENAME:
            return child
    return None


def render_default_template(vault_name: str, now_iso: str | None = None) -> str:
    """Render the default schema.md template for a new vault."""
    now_iso = now_iso or _now_iso()
    return (
        "---\n"
        "title: Wiki Schema\n"
        "type: schema\n"
        f"generated_by: marginalia schema init\n"
        f"generated_at: {now_iso}\n"
        f'vault_name: "{vault_name}"\n'
        'vault_purpose: "(Describe what this vault tracks — domain, audience, what it does NOT track)"\n'
        "entity_paths: [entities/]\n"
        "concept_paths: [concepts/]\n"
        "synthesis_paths: [synthesis/]\n"
        "raw_paths: [raw/]\n"
        "tag_taxonomy_ref: taxonomy.yml\n"
        "required_frontmatter: [title, tags, type]\n"
        "page_types: [entity, concept, synthesis]\n"
        "---\n"
        "\n"
        "# Wiki Schema\n"
        "\n"
        "This document declares the structure and conventions of this vault, readable\n"
        "by both humans and LLMs. Agents load this file before writing into the vault\n"
        "so they orient on its purpose and layout instead of inventing their own.\n"
        "\n"
        "## Purpose\n"
        "\n"
        "(What this wiki tracks. What it deliberately does NOT track. The narrower,\n"
        "the easier it is for an LLM to know whether a new source belongs here.)\n"
        "\n"
        "## Layout\n"
        "\n"
        "- **`entities/`** — One page per concrete subject (person, project, system).\n"
        "  Filename is the slug.\n"
        "- **`concepts/`** — Abstract ideas, patterns, principles.\n"
        "- **`synthesis/`** — Answers to questions, citing multiple sources. Created\n"
        "  by `marginalia query --save`.\n"
        "- **`raw/`** — Immutable raw sources (PDFs, web clips, transcripts). Read-only.\n"
        "  Excluded from `required_frontmatter` validation.\n"
        "\n"
        "## Growth loop\n"
        "\n"
        "1. `marginalia ingest <source>` — LLM creates an entity page from a raw\n"
        "   source, updates `index.md`, appends `log.md`.\n"
        "2. `marginalia query <question> --save` — LLM synthesizes an answer with\n"
        "   citations, files it back as a synthesis page.\n"
        "3. `marginalia scan` + `marginalia fix` + `marginalia discover` — periodic\n"
        "   hygiene and connection discovery.\n"
        "\n"
        "## LLM conventions\n"
        "\n"
        "- **Citation format**: `[[file-name]]` (wikilink) for every claim that comes\n"
        "  from a specific source.\n"
        "- **Page types**: `entity` (concrete subject), `concept` (abstract idea),\n"
        "  `synthesis` (answer with multiple sources).\n"
        "- **Required frontmatter**: every page must declare `title`, `tags`, `type`.\n"
        "\n"
        "---\n"
        "\n"
        "Generated by `marginalia schema init`. Edit to match your vault.\n"
        "Validate consistency: `marginalia schema validate`.\n"
        "Implements the LLM Wiki pattern (Karpathy gist `442a6bf`).\n"
    )


def parse_schema(schema_path: Path) -> dict[str, Any]:
    """Parse a schema.md file into a structured dict.

    Returns ``{"frontmatter": <dict>, "body": <str>, "path": <str>}``.
    Raises ``ValueError`` if the file has no parseable frontmatter.
    """
    content = schema_path.read_text(encoding="utf-8", errors="replace")
    fm = parse_frontmatter(content)
    if fm is None:
        raise ValueError(f"{schema_path}: no YAML frontmatter found")

    # Normalise list fields: parse_frontmatter may return string form "[a, b]"
    # for inline lists when no canonical handler matched.
    for key in LIST_FIELDS:
        if key in fm:
            fm[key] = _coerce_list(fm[key])

    # Strip frontmatter from body
    body = re.sub(r"^---\s*\n.*?\n---\s*\n?", "", content, count=1, flags=re.DOTALL)
    return {"frontmatter": fm, "body": body, "path": str(schema_path)}


def _coerce_list(value: Any) -> list[str]:
    """Normalise a frontmatter value into a list of strings.

    Handles inline ``[a, b]`` strings, already-parsed lists, single strings,
    and ``None``.
    """
    if value is None:
        return []
    if isinstance(value, list):
        return [str(v).strip() for v in value if str(v).strip()]
    if isinstance(value, str):
        s = value.strip()
        if s.startswith("[") and s.endswith("]"):
            inner = s[1:-1]
            return [p.strip().strip('"').strip("'") for p in inner.split(",") if p.strip()]
        return [s] if s else []
    return [str(value)]


def init_schema(vault: Path, force: bool = False) -> dict[str, Any]:
    """Create ``schema.md`` in the vault root.

    Returns ``{"action": "created"|"overwritten"|"skipped", "path": <str>, "reason": <str|None>}``.
    """
    target = vault / SCHEMA_FILENAME
    if target.exists() and not force:
        return {
            "action": "skipped",
            "path": str(target),
            "reason": "schema.md already exists (use --force to overwrite)",
        }
    template = render_default_template(vault_name=vault.name)
    target.write_text(template, encoding="utf-8")
    return {
        "action": "overwritten" if force and target.exists() else "created",
        "path": str(target),
        "reason": None,
    }


def show_schema(vault: Path) -> dict[str, Any]:
    """Return parsed schema for the given vault."""
    schema_path = find_schema(vault)
    if schema_path is None:
        return {"status": "missing", "path": str(vault / SCHEMA_FILENAME)}
    parsed = parse_schema(schema_path)
    return {"status": "ok", **parsed}


def validate_schema(vault: Path) -> dict[str, Any]:
    """Check the schema's claims against the actual vault state.

    For each declared path field, verify the directory exists and count
    Markdown files. For ``required_frontmatter``, scan the vault (excluding
    raw paths and schema.md) and report files missing any required field.

    Returns a structured report with ``status`` ``ok``|``issues``|``missing``.
    """
    schema_path = find_schema(vault)
    if schema_path is None:
        return {
            "status": "missing",
            "vault": str(vault),
            "schema_path": str(vault / SCHEMA_FILENAME),
            "message": "no schema.md (run: marginalia schema init)",
        }

    parsed = parse_schema(schema_path)
    fm = parsed["frontmatter"]

    checks: list[dict[str, Any]] = []

    # Path-field checks
    for field in PATH_FIELDS:
        paths = fm.get(field, [])
        for rel in paths:
            p = (vault / rel).resolve()
            try:
                p.relative_to(vault.resolve())
            except ValueError:
                checks.append({
                    "check": "path_escape",
                    "field": field,
                    "value": rel,
                    "passed": False,
                    "detail": "path escapes vault root",
                })
                continue
            exists = p.is_dir()
            md_count = 0
            if exists:
                md_count = sum(1 for _ in p.rglob("*.md"))
            checks.append({
                "check": "path_exists",
                "field": field,
                "value": rel,
                "passed": exists,
                "detail": f"{md_count} markdown files" if exists else "directory does not exist",
            })

    # tag_taxonomy_ref check
    tax_ref = fm.get("tag_taxonomy_ref")
    if tax_ref:
        tax_path = (vault / tax_ref).resolve()
        try:
            tax_path.relative_to(vault.resolve())
            tax_ok = tax_path.is_file()
        except ValueError:
            tax_ok = False
        checks.append({
            "check": "taxonomy_exists",
            "field": "tag_taxonomy_ref",
            "value": tax_ref,
            "passed": tax_ok,
            "detail": "file present" if tax_ok else "file not found",
        })

    # required_frontmatter check
    required = fm.get("required_frontmatter", [])
    excluded_prefixes = []
    for raw in fm.get("raw_paths", []):
        excluded_prefixes.append(raw.rstrip("/") + "/")

    missing_per_file: dict[str, list[str]] = {}
    files_checked = 0
    if required:
        for md in find_md_files([vault]):
            rel = md.relative_to(vault).as_posix()
            if rel.lower() == SCHEMA_FILENAME:
                continue
            if any(rel.startswith(pref) for pref in excluded_prefixes):
                continue
            files_checked += 1
            file_fm = parse_frontmatter(md.read_text(encoding="utf-8", errors="replace")) or {}
            missing = [f for f in required if f not in file_fm or file_fm.get(f) in (None, "")]
            if missing:
                missing_per_file[rel] = missing

    checks.append({
        "check": "required_frontmatter",
        "field": "required_frontmatter",
        "value": list(required),
        "passed": len(missing_per_file) == 0,
        "detail": f"{files_checked} files checked, {len(missing_per_file)} missing fields",
    })

    has_failures = any(not c["passed"] for c in checks)
    return {
        "status": "issues" if has_failures else "ok",
        "vault": str(vault),
        "schema_path": str(schema_path),
        "checks": checks,
        "missing_frontmatter_files": missing_per_file,
        "files_checked": files_checked,
    }
